### ISSUE TITLE
Error while creating index

### ISSUE THREAD

**Issue by riomario1** [amplab/snap#100]
Hi,

My Snap aligner is not working with the genome I am working with. I have 3 genome files and SNAP works with 2 of them but not third.

SNAP version 1.0beta.18.

Run:
./snap-aligner index /home/user/FILE_GENOME index-dir -locationSize 5

Error:
FASTA file contained a character that's not a valid base (or N): 'Y', full line 'CAAAACTGGCCAGAATAGACCAAAACTGCGAATTTTGACGAGTTCGGGTAACAGGACCCCGGGTTTCCCAAAACGTTCGGAGGCAAGCGGGAACCAAAATCAGTGAGTAATAGCTAACTAAGGGGCCAGAATAGGCCAAAACTGCGTATTTTGACGAGTTCCACAAGGGCTAAAACTGCGATTTTTGATGAGTTCCCGGTAAGCGGACCTCGGAGTTCTCGAAACGTTCGGATCACAACGGGACCCTAAATCAGTGACTAATAGCAGAGATAACTAGCGGGAATAGGCCAAAATTGCGAGTTTTCATGAGTTCCGTGGAATCGGTTCCCGGGGTTCCCAA.....
converting to 'N'.  This may happen again, but there will be no more warnings.
...
...
Indexing 1100000000 / 4833795607
Indexing 1200000000 / 4833795607
Killed
"

Any help?

**Comment by bolosky** [comment]
Most likely you’re running out of memory (or memory quota).  Given how many bases are in your FASTA, you’ll probably need more than 48GB.

You can try the -sm switch to the index build, which may or may not be enough to get you over the top (it’ll write some stuff generated during the middle of index build and write it out to disk to save memory).  If it isn’t enough, you’ll need to increase your quota or run on a machine with more memory.

How much memory does your machine have?

--Bill

**Comment by bolosky** [comment]
There’s code in SNAP to work with files in Hadoop, although I haven’t tried it out in a long time.

However, that won’t help you.  Your issue is that 31GB just isn’t enough memory to hold a SNAP index of a 4.8G base FASTA.  While SNAP is fast, it uses a hash table for an index which winds up using something like 10 bytes/base of FASTA (more or less; the exact amount depends on the content of the reference).  I’d try to find a machine with 64GB (or more) to run against this reference.  48GB probably isn’t enough when you allow room for the operating system, IO buffers, working memory, etc.

--Bill
