### ISSUE TITLE
Supplementary mappings

### ISSUE THREAD

**Issue by kcleal** [amplab/snap#152]
Hi,
Thanks for the nice tool. Just a question - I was wondering how snap chooses split-mappings a.k.a. supplementary alignments with a flag 2048? Is a minimum length of 50 bp used for example? How is the location of the supplementary alignment chosen - is it just based on the highest alignment score of candidate locations, or do the locations of the primary mappings influence the choice?

**Comment by bolosky** [comment]
No, we don't split reads.  If we have a single read that crosses an SV then if it's only a little bit the end will get soft clipped, otherwise it probably won't get aligned.

From: Kez Cleal ***@***.***>
Sent: Thursday, February 17, 2022 3:54 AM
To: amplab/snap ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [amplab/snap] Supplementary mappings (Issue #152)


Hi,
Thanks for the nice tool. Just a question - I was wondering if snap supports split-mappings a.k.a. supplementary alignments with a flag 2048? I can see from the documentation that secondary mappings can be output. Im interested in calling SVs and supplementary mappings are often very helpful for this purpose.

-
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Famplab%2Fsnap%2Fissues%2F152&data=04%7C01%7Cbolosky%40microsoft.com%7Ca86e52e54d9843a2465a08d9f20c3e67%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637806956681331651%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=iDy7xZc1mZtqUK1v90FVWjO%2FZ2PVQBTCyRGoO4EHooU%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAHPTWL5UVMLAVAYKLWHCTDU3TOXBANCNFSM5OUOOXEQ&data=04%7C01%7Cbolosky%40microsoft.com%7Ca86e52e54d9843a2465a08d9f20c3e67%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637806956681331651%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DdWtoE3W13WgoQ9o3LHURFnmDN2Clmjw5bxA%2FTdTx%2Bg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cbolosky%40microsoft.com%7Ca86e52e54d9843a2465a08d9f20c3e67%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637806956681331651%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=quvqb5wYqQTtqb8bnmqKGKzCnFZ0YJdFIeN9azoK8bA%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cbolosky%40microsoft.com%7Ca86e52e54d9843a2465a08d9f20c3e67%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637806956681331651%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=R9HMxap7DAdfWgseCs2L%2B%2F788FKzRA1uTs8IVSRGESI%3D&reserved=0>.
