### ISSUE TITLE
Performance tweaking wrt parallel runs

### ISSUE THREAD

**Issue by matthdsm** [amplab/snap#157]
Hi,

I'm trying to run multiple instances of snap (in docker) through a workflow manager. However, I'm noticing only one of the instances is using the full CPU capacity at the time.

Are there any settings to tweak so we can fully use the cpu's of the entire node?

![htop screengrab](https://user-images.githubusercontent.com/11850640/186415785-d4d9258f-2072-459a-af08-8553e920546f.png)

Currently, we're using default settings with sorting enabled on 18 threads per instance. I tried using `-map-` but that didn't help.

Thanks for the info
Matthias

**Comment by matthdsm** [comment]
I also noticed when monitoring the processes that each thread uses on average 30% with peaks to 50% of the allocated core capacity.

**Comment by slw287r** [comment]
Multiple snap-aligner instances will use up to the number of threads specified by `-t`. Try `-t 72` for each instance to see the difference.

**Comment by matthdsm** [comment]
So to be clear:
when I run 3 instances with each 18 cores allocated (`-t 18`), all three instances will be limited to **_the same_** 18 cores?
I would assume they each take up the full CPU of the 18 allocated cores, so 18 cores/instance , thus filling the entire node.

**Comment by bolosky** [comment]
It's because SNAP is binding the threads to the low numbered cores, so all of the instances are running on cores 0-17.

Try -b-, which will turn this off and let the OS schedule threads as it sees fit.

-map- is not a good idea for this.  In the default mode there will be one copy of the index in memory, with -map- there will be one copy per instance of SNAP.  It's also slower to load.

From: Matthias De Smet ***@***.***>
Sent: Wednesday, August 24, 2022 5:18 AM
To: amplab/snap ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [amplab/snap] Performance tweaking wrt parallel runs (Issue #157)


Hi,

I'm trying to run multiple instances of snap (in docker) through a workflow manager. However, I'm noticing only one of the instances is using the full CPU capacity at the time.

Are there any settings to tweak so we can fully use the cpu's of the entire node?

[htop screengrab]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F11850640%2F186415785-d4d9258f-2072-459a-af08-8553e920546f.png&data=05%7C01%7Cbolosky%40microsoft.com%7C3860c682827d494c8e9808da85cab914%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637969402979086522%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TgnoaKmsdR3i%2BGghiRj3SrP%2FL4l2zJZTQb5kfkOaZv0%3D&reserved=0>

Currently, we're using default settings with sorting enabled on 18 threads per instance. I tried using -map- but that didn't help.

Thanks for the info
Matthias

-

**Comment by matthdsm** [comment]
Oh wow, adding `-b-` has a tremendous effect on efficiency! I can now see all fully cores used.
Is there a reason this isn't default behaviour?

**Comment by bolosky** [comment]
The intent is to run one instance of snap at a time.  Typically it can saturate all of the cores.  When that happens, moving threads from core to core causes the cache state to have to move which can be expensive.  Binding the threads to cores prevents this from happening.

I'm not sure why you're not seeing 100% use when you run just one instance at a time if your IO system is fast enough to keep up, which it must be if you can get 100% with multiple instances.

**Comment by matthdsm** [comment]
I'm working on a heterogenous cluster through a workflow manager, so the number is threads is set before scheduling.
This means I can't use the full node, since I've no idea where it will be scheduled.
I'm thinking we only see about 30% usage per thread since there were 3 instances running on the same 18 cores, which would mean all 3 instances are competing for the same CPU.

Background info (for this node):
- Ubuntu 18.04.5 LTS
- Intel(R) Xeon(R) CPU E5-2698
- CephFS backend

**Comment by bolosky** [comment]
If you just don't specify -t it defaults to the number of cores on the machine (unlike seemingly every other piece of software out there for whatever reason).  So if you arrange to just have one instance of snap per machine at a time then it should do the right thing.

But what you're doing seems to work fine, too.

**Comment by matthdsm** [comment]
Allright, thanks for all the help!
