### ISSUE TITLE
snap index not creating GenomeIndexHash%d files

### ISSUE THREAD

**Issue by ericenns** [amplab/snap#74]
I am using snap 1.0beta.18 on linux (ubuntu 14.04.4 LTS and centos 7.2) and index is failing to create GenomeIndexHash%d file without giving an error message so it appears everything works until I attempt to use snap to align which errors saying it can't find GenomeIndexHash0000

**Comment by bolosky** [comment]
Something very weird is going on, because 1.0beta.18 didn’t use GenomeIndexHash00000-style files.  Those have been gone for years (I consolidated them into a single GenomeIndexHash file, because for some index build parameters you could wind up with tens of thousands of the GenomeIndexHash files, which was slow and unwieldy).  As best I can tell from looking at git history, that went away in 1.0alpha.48 in December, 2013.

I’d check to make sure that you’re running the same version of SNAP to build the index and run the alignment (though, really, it’s supposed to detect an index format mismatch and give an error about that).

--Bill

**Comment by ericenns** [comment]
So it looks like SURPI was calling snap v0.5.14 instead of the version I indexed it with. I fixed that issue and am no longer getting that error thanks.
