### ISSUE TITLE
SNAP doesn't support full FASTA/IUBMB/IUPAC sequence representation

### ISSUE THREAD

**Issue by taltman** [amplab/snap#80]
It seems that SNAP only supports the following base symbols: ACTGN, while FASTA supports a richer alphabet coming from the IUBMB/IUPAC:

https://en.wikipedia.org/wiki/FASTA_format

See error message below, where valid FASTA character 'R' (A or G; "puRine") is flagged. 

At the very least, SNAP should be aware of the difference between valid characters (e.g., "R-" and invalid ones (e.g., "#*@@#(&$"), so that warnings are thrown only for the latter, and not the former (even if the former are silently converted into 'N' internally).

```
Loading FASTA file '/dev/shm/taltman/Martin_etal_TextS3_13Dec2011.fasta' into memory...
FASTA file contained a character that's not a valid base (or N): 'R', full line 'CACGCGTCGAAAAGGTAAGTACTTCTTTACCGGGTATGTGTTRATTTTTATGACGTCACT';
converting to 'N'.  This may happen again, but there will be no more warnings.
```

**Comment by taltman** [comment]
Also, it would be helpful if SNAP printed out the line number (or the FASTA defline identifier for the current entry) where the invalid character was detected, since SNAP already is noting that internal state.

**Comment by bolosky** [comment]
There’s essentially no way that SNAP will ever be able to deal gracefully with multi-bases like R, the idea that there are four bases is baked into the code way too deeply.  So, it seems reasonable to me to put out a warning when it gets a reference with one of these bases in it to let the user know that it’s going to be treated like an N (which in SNAP never matches anything, even Ns in the read).

I suppose that the warning could be better worded, but I’m inclined to keep it rather than making it go away.

--B
