### ISSUE TITLE
Error- GzipDataReader: inflate failed with -2

### ISSUE THREAD

**Issue by MrOlm** [amplab/snap#87]
When running SNAP on gziped reads, I get the following log:

```
Welcome to SNAP version 1.0beta.23.

Loading index from directory... 1s.  265549280 bases, seed size 20
Aligning.
GzipDataReader: inflate failed with -2
SNAP exited with exit code 1 from line 1659 of file SNAPLib/DataReader.cpp
```

From the zlib manual ( http://zlib.net/manual.html ), the -2 exit code from zlib corresponds to:

```
Z_STREAM_ERROR if the stream structure was inconsistent (for example next_in or next_out was Z_NULL, or the state was inadvertently written over by the application)
```

Any idea what could be causing this? I've confirmed that the program is linked to the correct zlib library, and when I decompress the same reads and run it again it works.

Thanks,
-Matt

**Comment by bolosky** [comment]
Does it happen consistently on this input file, or only once?

From your comment, I’m assuming that you were able to gunzip the file successfully, so it’s not just that your input file is corrupt (which is my first reading of that error message).

If it’s repeatable, maybe you’d be willing to share the file with me so I can debug it.


--Bill

**Comment by MrOlm** [comment]
I don't think it's a problem with the input file for two reasons: 
-  the input file works on my system when uncompressed
-  the input file works on another system I tested when compressed

Any other ideas what could be causing this problem on my machine? As I said I'm able to run SNAP fine on uncompressed files, so I don't think it's a problem with my SNAP installation.

Thanks again,
-Matt

**Comment by bolosky** [comment]
Maybe there’s something that’s in the way it’s compressed that the version of zlib linked with SNAP can’t handle.  All that’s happening in SNAP to generate this error message is that it’s getting an error back from the inflate call in zlib.  Here’s the code in question:

        status = inflate(zstream, mode == SingleBlock ? Z_NO_FLUSH : Z_FINISH);
        if (status < 0 && status != Z_BUF_ERROR) {
            WriteErrorMessage("GzipDataReader: inflate failed with %d\n", status);
            soft_exit(1);
        }


The only other thought that I have is that it has too small of a buffer, which you can fix by increasing the –xf parameter.  However, that’s supposed to generate a different error from zlib, and when SNAP detects it it prints out an error suggesting that you increase –xf.

You can also try running the dev version (from the dev branch in github, current version 1.0dev.100), I’m not sure if all of the fixes are in the release version, so maybe that’s why you’re seeing the error message instead of the –xf one.

And yes, I’m LONG overdue for pushing the dev version into release.

--B

**Comment by lpryszcz** [comment]
I have similar issue that happens consistently with precompiled version 1.0beta18 (from your website), but works fine with 1.0beta.23 (shipped through anaconda). Any idea?

**Comment by bolosky** [comment]
This got fixed with updates to deal with new versions of zlib, which have been in the code for a while.  I'm closing this now.
